-- Baheth Masr crawler database schema for Supabase/PostgreSQL
-- Run this script in Supabase SQL Editor.
-- The two current sites are seeded as category: ديني.

create table if not exists public.crawler_sites (
  id bigint generated by default as identity primary key,
  url text not null unique,
  category text not null default 'ديني',
  crawl_status text not null default 'pending',
  discovery_cursor jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.crawler_sites
  add column if not exists category text not null default 'ديني';

create table if not exists public.crawler_queue (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.crawler_sites(id) on delete cascade,
  url text not null unique,
  crawl_status text not null default 'pending',
  crawl_attempts integer not null default 0,
  worker_id text,
  processing_started_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.crawler_results (
  id bigint generated by default as identity primary key,
  url text not null unique,
  title text not null default '',
  description text not null default '',
  icon_url text not null default '',
  keywords text not null default '',
  snippet text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.crawler_attempts (
  id bigint generated by default as identity primary key,
  queue_id bigint references public.crawler_queue(id) on delete set null,
  site_id bigint references public.crawler_sites(id) on delete set null,
  worker_id text,
  status text not null default 'started',
  error text,
  metadata jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists crawler_sites_status_idx
  on public.crawler_sites (crawl_status, id);
create index if not exists crawler_queue_status_idx
  on public.crawler_queue (crawl_status, id);
create index if not exists crawler_queue_site_id_idx
  on public.crawler_queue (site_id, id);
create index if not exists crawler_queue_processing_idx
  on public.crawler_queue (processing_started_at)
  where crawl_status = 'processing';
create index if not exists crawler_results_url_idx
  on public.crawler_results (url);
create index if not exists crawler_attempts_queue_id_idx
  on public.crawler_attempts (queue_id, id);

-- Claim pending pages safely when multiple workers run at once.
create or replace function public.claim_crawler_queue(
  p_limit integer,
  p_worker_id text
)
returns setof public.crawler_queue
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with picked as (
    select q.id
    from public.crawler_queue q
    where q.crawl_status = 'pending'
    order by q.id
    limit greatest(1, least(coalesce(p_limit, 1), 2000))
    for update skip locked
  )
  update public.crawler_queue q
  set crawl_status = 'processing',
      worker_id = p_worker_id,
      processing_started_at = now(),
      crawl_attempts = q.crawl_attempts + 1,
      updated_at = now()
  from picked
  where q.id = picked.id
  returning q.*;
end;
$$;

-- Finish one claimed page.
create or replace function public.finish_crawler_queue(
  p_id bigint,
  p_status text,
  p_error text default null
)
returns public.crawler_queue
language sql
security definer
set search_path = public
as $$
  update public.crawler_queue
  set crawl_status = p_status,
      worker_id = null,
      processing_started_at = null,
      updated_at = now()
  where id = p_id
  returning *;
$$;

-- Return pages abandoned by a crashed worker to pending.
create or replace function public.recover_stale_crawler_queue(
  p_stale_minutes integer default 30
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  recovered integer;
begin
  update public.crawler_queue
  set crawl_status = 'pending',
      worker_id = null,
      processing_started_at = null,
      updated_at = now()
  where crawl_status = 'processing'
    and processing_started_at < now() - make_interval(mins => greatest(1, p_stale_minutes));
  get diagnostics recovered = row_count;
  return recovered;
end;
$$;

-- Keep the tables private. GitHub Actions uses the service-role key.
alter table public.crawler_sites enable row level security;
alter table public.crawler_queue enable row level security;
alter table public.crawler_results enable row level security;
alter table public.crawler_attempts enable row level security;

revoke all on table public.crawler_sites from anon, authenticated;
revoke all on table public.crawler_queue from anon, authenticated;
revoke all on table public.crawler_results from anon, authenticated;
revoke all on table public.crawler_attempts from anon, authenticated;

revoke all on function public.claim_crawler_queue(integer, text) from public, anon, authenticated;
revoke all on function public.finish_crawler_queue(bigint, text, text) from public, anon, authenticated;
revoke all on function public.recover_stale_crawler_queue(integer) from public, anon, authenticated;
grant execute on function public.claim_crawler_queue(integer, text) to service_role;
grant execute on function public.finish_crawler_queue(bigint, text, text) to service_role;
grant execute on function public.recover_stale_crawler_queue(integer) to service_role;

-- Current seed sites.
insert into public.crawler_sites (url, category)
values
  ('https://quran.com/ar', 'ديني'),
  ('https://misrquran.gov.eg/', 'ديني')
on conflict (url) do update
set category = excluded.category,
    updated_at = now();
