import { db, resultsDb, canonicalize } from './db.mjs';
import { extractHtml } from './extract.mjs';
import { discover } from './discovery.mjs';

const timeoutMs=Number(process.env.CRAWLER_TIMEOUT_MS||15000),limit=Number(process.env.CRAWLER_LIMIT||10),delayMs=Number(process.env.CRAWLER_DELAY_MS||300);const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function createRun(runType){const row=db.prepare(`INSERT INTO crawl_runs (run_type,status,started_at) VALUES (?, 'running', CURRENT_TIMESTAMP)`).run(runType);return row.lastInsertRowid;}
function createTargets(runId,runType){const sites=db.prepare(`SELECT id AS site_id,url,priority FROM sites WHERE status='active' ORDER BY priority DESC LIMIT ?`).all(limit);const insert=db.prepare(`INSERT INTO crawl_targets (run_id,target_type,site_id,url,canonical_url,priority,reason) VALUES (?, 'site', ?, ?, ?, ?, ?)`);for(const site of sites)insert.run(runId,site.site_id,site.url,canonicalize(site.url),site.priority,runType);}
function promoteSeedDiscoveries(runId){const rows=db.prepare(`SELECT id,discovered_url,canonical_url,discovery_source FROM crawl_discoveries WHERE run_id=? AND discovery_source IN ('manual','duckduckgo') AND status='pending' LIMIT ?`).all(runId,Math.max(limit,1));const insert=db.prepare(`INSERT INTO crawl_targets (run_id,target_type,url,canonical_url,priority,reason) VALUES (?, 'discovered_url', ?, ?, 80, ?)`);for(const row of rows){insert.run(runId,row.discovered_url,row.canonical_url,row.discovery_source);db.prepare(`UPDATE crawl_discoveries SET status='queued' WHERE id=?`).run(row.id);}return rows.length;}
async function fetchOne(url){const started=Date.now(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(url,{redirect:'follow',signal:controller.signal,headers:{'user-agent':'BahethMasrCrawler/0.1 (+staging)'}});const contentType=response.headers.get('content-type')||'';const body=contentType.includes('text/html')?await response.text():'';return{response,body,contentType,duration:Date.now()-started};}catch(error){return{error:String(error),duration:Date.now()-started};}finally{clearTimeout(timer);}}
function addPageDiscoveries(runId,siteId,sourceUrl,meta){let count=0;for(const link of meta.links){const canonicalUrl=canonicalize(link.url);if(!canonicalUrl)continue;const exists=db.prepare('SELECT 1 FROM site_pages WHERE url=? UNION SELECT 1 FROM crawl_discoveries WHERE canonical_url=?').get(link.url,canonicalUrl);if(exists)continue;try{db.prepare(`INSERT INTO crawl_discoveries (run_id,source_site_id,discovered_url,canonical_url,discovery_source,discovered_from_url,title_hint,description_hint) VALUES (?,?,?,?,?,?,?,?)`).run(runId,siteId,link.url,canonicalUrl,'html_link',sourceUrl,meta.title,meta.description);count++;}catch{}}return count;}
const emptyMeta=()=>({title:'',description:'',summary:'',iconUrl:'',extractedText:'',contentHash:'',links:[],internalLinks:[],externalLinks:[],socialLinks:[]});

export async function run(runType='daily_check'){const runId=createRun(runType);const queries=String(process.env.CRAWLER_DDG_QUERIES||'').split('|').map(x=>x.trim()).filter(Boolean);let discovered=await discover(runId,{queries,manualUrl:process.env.CRAWLER_MANUAL_URL||''});createTargets(runId,runType);promoteSeedDiscoveries(runId);const targets=db.prepare('SELECT * FROM crawl_targets WHERE run_id=? ORDER BY priority DESC,id').all(runId);let success=0,failed=0,changed=0;
 for(const target of targets){db.prepare(`UPDATE crawl_targets SET status='processing',attempts=attempts+1,last_attempt_at=CURRENT_TIMESTAMP WHERE id=?`).run(target.id);const result=await fetchOne(target.url);let observation;
  if(result.error){failed++;observation={crawlStatus:'network_error',httpStatus:null,responseUrl:'',contentType:'',body:'',meta:emptyMeta(),error:result.error};}else{const meta=result.body?extractHtml(result.body,result.response.url):emptyMeta();const ok=result.response.status>=200&&result.response.status<400;if(ok)success++;else failed++;observation={crawlStatus:ok?'success':'http_error',httpStatus:result.response.status,responseUrl:result.response.url,contentType:result.contentType,body:result.body,meta,error:''};if(meta.contentHash&&target.site_id){const old=db.prepare('SELECT content_hash FROM site_pages WHERE site_id=? ORDER BY id LIMIT 1').get(target.site_id);if(old?.content_hash&&old.content_hash!==meta.contentHash)changed++;}discovered+=addPageDiscoveries(runId,target.site_id,target.url,meta);}
  const m=observation.meta;resultsDb.prepare(`INSERT INTO crawl_results (source_run_id,run_type,source_target_id,requested_url,canonical_url,response_url,http_status,crawl_status,content_type,content_length,title,description,summary,icon_url,extracted_text,content_hash,links_json,internal_links_json,external_links_json,social_links_json,discovered_links_count,duration_ms,error_message) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(runId,runType,target.id,target.url,canonicalize(target.url),observation.responseUrl,observation.httpStatus,observation.crawlStatus,observation.contentType,observation.body?.length||0,m.title,m.description,m.summary,m.iconUrl,m.extractedText,m.contentHash,JSON.stringify(m.links),JSON.stringify(m.internalLinks),JSON.stringify(m.externalLinks),JSON.stringify(m.socialLinks),m.links.length,result.duration,observation.error);db.prepare(`UPDATE crawl_targets SET status=? WHERE id=?`).run(observation.crawlStatus==='success'?'completed':'failed',target.id);await sleep(delayMs);}
 db.prepare(`UPDATE crawl_runs SET status='completed',finished_at=CURRENT_TIMESTAMP,processed_count=?,success_count=?,failed_count=?,changed_count=?,discovered_count=? WHERE id=?`).run(targets.length,success,failed,changed,discovered,runId);return{runId,runType,total:targets.length,success,failed,changed,discovered,ddg_queries:queries.length,manual_url:Boolean(process.env.CRAWLER_MANUAL_URL),results_database:'db/results.sqlite'};}
