import crypto from 'node:crypto';
import * as cheerio from 'cheerio';
import { classifyContent } from './classify.mjs';
const NON_CONTENT='script,style,noscript,template,svg,canvas,iframe,object,embed,form,button,input,select,textarea';
const BOILERPLATE='nav,header,footer,aside,.sidebar,.navbar,.navigation,.social,.share,.comments,#comments,.cookie,.popup,.advert,.ads,.ad,.sidebar .widget,.footer .widget';
const SOCIAL_HOSTS=['facebook.com','fb.com','youtube.com','youtu.be','x.com','twitter.com','instagram.com','tiktok.com','linkedin.com','telegram.me','t.me'];
const SNIPPET_NOISE=/^(الرئيسية|من نحن|اتصل بنا|سياس[ةه] الخصوصية|حقوق النشر|عرض المزيد|رسائل أقدم|social widget)$/i;
function cleanText(value=''){return String(value).replace(/\u00a0/g,' ').replace(/[ \t]+/g,' ').replace(/\s*\n\s*/g,'\n').replace(/\n{3,}/g,'\n\n').trim();}
function extractUsefulText($){$(NON_CONTENT).remove();const root=$('body').get(0);if(!root)return '';const scoped=$(root);scoped.find(BOILERPLATE).remove();const blocks=[];scoped.find('article,div.post,div.post-body,.entry-content,.post-content,.widget-content,h1,h2,h3,h4,h5,h6,p,li,blockquote,pre,td,th').each((_,el)=>{const text=cleanText($(el).text());if(text.length>=2&&!blocks.includes(text))blocks.push(text);});const structured=cleanText(blocks.join('\n'));return(structured.length>=80?structured:cleanText(scoped.text())).slice(0,50000);}
function extractArticleText($){const candidates=[];for(const selector of ['article','.post-body','.entry-content','.post-content','div.post']){$(selector).each((_,el)=>{const text=cleanText($(el).find('h1,h2,h3,h4,h5,h6,p,blockquote,pre,li').map((__,node)=>cleanText($(node).text())).get().filter(Boolean).join('\n')||$(el).text());if(text.length>=80&&!candidates.includes(text))candidates.push(text);});}return candidates.sort((a,b)=>b.length-a.length)[0]||'';}
function articleDescription(title,articleText){const parts=articleText.split(/\n+/).map(cleanText).filter(x=>x.length>=25&&!SNIPPET_NOISE.test(x));const text=parts.slice(0,3).join(' ').replace(/\s+/g,' ').trim();return text.replace(new RegExp(`^${title.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\s*[-—:]?\\s*`,'i'),'').slice(0,500).trim();}
function cleanUrlCandidate(raw,responseUrl){if(!raw||/^(mailto:|tel:|javascript:|#|data:)/i.test(raw))return '';let value=raw.trim().replace(/^['"\s]+|['"\s]+$/g,'');const embedded=value.match(/https?:\/\/[^\s"'<>]+/i);if(embedded)value=embedded[0];if(/https?:\/\/.*https?:\/\//i.test(value))return '';try{const u=new URL(value,responseUrl);if(!['http:','https:'].includes(u.protocol)||/\/feeds(?:\/|$)|comments\/default|(?:^|\/)(?:atom|rss)(?:\.xml)?$/i.test(u.pathname))return '';return u.toString();}catch{return '';}}
function isSocial(host){const h=host.toLowerCase().replace(/^www\./,'');return SOCIAL_HOSTS.some(x=>h===x||h.endsWith(`.${x}`));}
function makeSummary(title,description,text){let content=text.split(/\n+/).map(cleanText).filter(Boolean).join(' ').replace(/\s+/g,' ').replace(/جاري التحويل\.{2,}\s*اضغط هنا إذا لم يتم التحويل تلقائياً/gi,'').trim();if(title)content=content.split(title).join(' ').replace(/\s+/g,' ').trim();if(content)return content.slice(0,500);if(description)return description.slice(0,500);return title.slice(0,500);}
function makeSearchSnippet(title,description,summary,text){const content=text.split(/\n+/).map(cleanText).filter(x=>x&&!SNIPPET_NOISE.test(x));let s=[description||summary,...content].filter(Boolean).join(' ').replace(/\s+/g,' ').trim();if(title&&!s.toLowerCase().startsWith(title.toLowerCase()))s=`${title} — ${s}`;return s.slice(0,320);}
function quality(title,description,text,contentType){const combined=`${title} ${description} ${text}`;const arabic=(combined.match(/[\u0600-\u06ff]/g)||[]).length;const latin=(combined.match(/[A-Za-z]/g)||[]).length;const api=!/html/i.test(contentType)||(!title&&!description&&text.length<1000);const dynamic=Boolean(title)&&text.length<20;const challenge=/unusual traffic|not a robot|verify you are human|captcha|automatically detects requests/i.test(combined);const genericTitle=/^(codenex|موقع\s+codenex1\.blogspot\.com)$/i.test(title.trim());let status='good';if(api)status='not_indexable_api';else if(challenge)status='blocked_challenge';else if(dynamic)status='dynamic_content';else if((text.length<300&&!description)||(genericTitle&&text.length<500))status='thin_content';return{qualityStatus:status,reviewStatus:status==='good'?'accepted':'review',detectedLanguage:arabic>latin?'ar':latin>0?'latin':'unknown',isDynamic:dynamic,isApi:api,isChallenge:challenge};}
export function extractHtml(html,responseUrl,contentType='text/html'){const $=cheerio.load(html||'');const baseHost=new URL(responseUrl).hostname.replace(/^www\./,'');const rawTitle=cleanText($('title').first().text())||cleanText($('meta[property="og:title" i]').attr('content')||'');const title=/^https?:\/\//i.test(rawTitle)?(baseHost.includes('holyquranradio')?'Holy Quran Radio':'موقع '+baseHost):rawTitle;const rawDescription=cleanText($('meta[name="description" i]').attr('content')||$('meta[property="og:description" i]').attr('content')||'');const icon=$('link[rel~="icon" i]').attr('href')||$('meta[property="og:image" i]').attr('content')||'';const articleText=extractArticleText($);const text=extractUsefulText($);const pagePath=new URL(responseUrl).pathname;const isBlogContent=/\/\d{4}\/\d{2}\//.test(pagePath)||/^\/p\//.test(pagePath);const contentDescription=isBlogContent?articleDescription(title,articleText):'';const pageDescription=isBlogContent?(contentDescription||''):rawDescription;const description=pageDescription||makeSummary(title,'',text).slice(0,500);const summary=makeSummary(title,'',text);const searchSnippet=makeSearchSnippet(title,description,summary,text);const q=quality(title,description,text,contentType);const classification=classifyContent({title,description,summary,extractedText:text,sourceUrl:responseUrl});const contentHash=crypto.createHash('sha256').update(`${title}\n${description}\n${summary}\n${searchSnippet}\n${text}`).digest('hex');const links=[];const seen=new Set();$('a[href]').each((_,el)=>{const url=cleanUrlCandidate($(el).attr('href'),responseUrl);if(!url||seen.has(url))return;seen.add(url);const host=new URL(url).hostname.replace(/^www\./,'');links.push({url,anchorText:cleanText($(el).text()).slice(0,200),type:isSocial(host)?'social':host===baseHost?'internal':'external'});});let iconUrl='';try{iconUrl=icon?new URL(icon,responseUrl).toString():'';}catch{}return{title,description,summary,searchSnippet,iconUrl,extractedText:text,contentHash,...q,...classification,links:links.slice(0,100),internalLinks:links.filter(x=>x.type==='internal').map(x=>x.url),externalLinks:links.filter(x=>x.type==='external').map(x=>x.url),socialLinks:links.filter(x=>x.type==='social').map(x=>x.url)};}
