import http from 'node:http';
import { spawn } from 'node:child_process';
import Database from 'better-sqlite3';
import fs from 'node:fs';

const linksDb='/tmp/stress-links.sqlite', resultsDb='/tmp/stress-results.sqlite', count=Number(process.env.STRESS_URL_COUNT||50);
for(const file of [linksDb,resultsDb])try{fs.unlinkSync(file)}catch{}
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://127.0.0.1');if(url.pathname.startsWith('/page-')){const n=url.pathname.match(/page-(\d+)/)?.[1]||'0';const links=Array.from({length:5},(_,i)=>`<a href="/page-${(Number(n)+i+1)%count}">صفحة ${i}</a>`).join('');const body=`<!doctype html><html lang="ar"><head><title>صفحة اختبار ${n}</title><meta name="description" content="وصف اختبار ضغط للزاحف"></head><body><main><h1>صفحة اختبار ${n}</h1><p>${'نص مفيد للاختبار '.repeat(60)}</p>${links}</main></body></html>`;res.writeHead(200,{'content-type':'text/html; charset=utf-8'});return res.end(body)}res.writeHead(404,{'content-type':'text/plain'});res.end('not found')});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const port=server.address().port;const env={...process.env,CRAWLER_INPUT_DB_PATH:linksDb,CRAWLER_RESULTS_DB_PATH:resultsDb,CRAWLER_LIMIT:String(count),CRAWLER_FETCH_MODE:'http',CRAWLER_CONCURRENCY:'4',CRAWLER_RETRIES:'0',CRAWLER_TIMEOUT_MS:'10000',CRAWLER_MANUAL_URL:`http://127.0.0.1:${port}/page-0`,CRAWLER_DDG_QUERIES:''};
function run(args){return new Promise((resolve,reject)=>{const p=spawn(process.execPath,['crawler/src/cli.mjs',...args],{env,stdio:['ignore','pipe','pipe']});let out='',err='';p.stdout.on('data',x=>out+=x);p.stderr.on('data',x=>err+=x);p.on('close',code=>code?reject(new Error(`${args.join(' ')} failed: ${err||out}`)):resolve(out));});}
await run(['init']);const db=new Database(linksDb);db.exec('DELETE FROM crawl_discoveries; DELETE FROM site_pages; DELETE FROM sites;');const insert=db.prepare("INSERT INTO sites(url,name,status,priority) VALUES(?,?, 'active',70)");for(let i=0;i<count;i++)insert.run(`http://127.0.0.1:${port}/page-${i}`,`Stress page ${i}`);db.close();const started=Date.now();const output=await run(['manual']);const elapsed=Date.now()-started;const rdb=new Database(resultsDb,{readonly:true});const stats={total:rdb.prepare('SELECT COUNT(*) n FROM crawl_results').get().n,success:rdb.prepare("SELECT COUNT(*) n FROM crawl_results WHERE crawl_status='success'").get().n,failed:rdb.prepare("SELECT COUNT(*) n FROM crawl_results WHERE crawl_status<>'success'").get().n,review:rdb.prepare('SELECT COUNT(*) n FROM crawl_review_items').get().n,quarantine:rdb.prepare('SELECT COUNT(*) n FROM crawl_quarantine').get().n};rdb.close();server.close();if(stats.total<count||stats.failed>0||stats.quarantine>0)throw new Error(`stress failure ${JSON.stringify(stats)}`);console.log(JSON.stringify({ok:true,count,elapsed_ms:elapsed,requests_per_second:Number((stats.total/(elapsed/1000)).toFixed(2)),stats,cli:JSON.parse(output)},null,2));
